### ISSUE TITLE
searchNotes 不可用

### ISSUE THREAD

**Issue by Boom199801** [C-L-STARK/xhs_api#1]
<img width="800" alt="image" src="https://github.com/user-attachments/assets/bc615f94-656b-48af-b4a7-f01005214906">
大佬，这边关于搜索帖子的内容不可用

**Comment by C-L-STARK** [comment]
这里搜索出来，要额外调用  getNodeById 方法获得帖子内容的。

**Comment by C-L-STARK** [comment]
<img width="622" alt="image" src="https://github.com/user-attachments/assets/b78a0ede-0dd2-4a56-8ab0-28e6629d9738">

**Comment by Boom199801** [comment]
好滴，谢谢大佬
