### ISSUE TITLE
添加额外api

### ISSUE THREAD

**Issue by I-BlueDragon** [C-L-STARK/xhs_api#2]
可以添加获取用户所有笔记的api吗？

**Comment by C-L-STARK** [comment]
现在已经有这个API了。您看下文档；
需要您自己写一个循环，去遍历出来用户的所有笔记。

`getNoteListByUserId` 中有一个 `cursor` 的字段；就是用来做分页遍历的。

**Comment by I-BlueDragon** [comment]
> 现在已经有这个API了。您看下文档； 需要您自己写一个循环，去遍历出来用户的所有笔记。
> 
> `getNoteListByUserId` 中有一个 `cursor` 的字段；就是用来做分页遍历的。

好的非常感谢您
