### ISSUE TITLE
访问异常

### ISSUE THREAD

**Issue by I-BlueDragon** [C-L-STARK/xhs_api#3]
使用getNoteById来访问用户笔记时出现data: { code: 300013, success: false, msg: '访问频次异常，请勿频繁操作或重启试试', data: {} }
但是status: 200,
statusText: 'OK'基础信息正常

过很长一段时间后才会回复，期间重新登陆以及更换cookie无用

**Comment by C-L-STARK** [comment]
访问频次异常；
目前一个cookie大概访问100-200次或者短时间内高频访问就会出现该问题。暂时无法避免。

只能使用接码平台注册大量的小号 ~
